
export const SIDE_MENU = 'SIDE_MENU'

export const USER = 'USER'

// MyTask Actions
export const TASKS = 'TASKS'
export const USER_SELECT = 'USER_SELECT'

export const TASK_DETAIL_ID = 'TASK_DETAIL_ID'
// Task Detail Actions
export const TASK_DETAIL = 'TASK_DETAIL'
export const TASK_DETAIL_CREATED_DT = 'TASK_DETAIL_CREATED_DT'
export const TASK_DETAIL_TITLE = 'TASK_DETAIL_TITLE'

export const TASK_DETAIL_STAKEHOLDER = 'TASK_DETAIL_STAKEHOLDER'
export const TASK_DETAIL_REVIEW_DT = 'TASK_DETAIL_REVIEW_DT'
export const TASK_DETAIL_ASSIGNED = 'TASK_DETAIL_ASSIGNED'
export const TASK_DETAIL_SUMMARY = 'TASK_DETAIL_SUMMARY'
export const TASK_DETAIL_STATUS_MACRO = 'TASK_DETAIL_STATUS_MACRO'
export const TASK_DETAIL_STATUS_MICRO = 'TASK_DETAIL_STATUS_MICRO'
