
export const SIDE_MENU = 'SIDE_MENU'

export const USER = 'USER'

// TASKLIST TASKS
export const TASKS = 'TASKS'
export const SORT = 'SORT'
export const COMPLETE_STATE_TASK = 'COMPLETE_STATE_TASK'
export const ADD_STATE_TASK = 'ADD_STATE_TASK'
export const UPDATE_STATE_TASK = 'COMPLETE_STATE_TASK'
export const UPDATE_STATE_REVIEW_DT = 'UPDATE_STATE_REVIEW_DT'


export const USER_SELECT = 'USER_SELECT'

export const TASK_DETAIL_ID = 'TASK_DETAIL_ID'
// Task Detail Actions
export const TASK_DETAIL = 'TASK_DETAIL'
export const TASK_DETAIL_CREATED_DT = 'TASK_DETAIL_CREATED_DT'
export const TASK_DETAIL_TITLE = 'TASK_DETAIL_TITLE'
export const TASK_DETAIL_STAKEHOLDER = 'TASK_DETAIL_STAKEHOLDER'
export const TASK_DETAIL_REVIEW_DT = 'TASK_DETAIL_REVIEW_DT'
export const TASK_DETAIL_ASSIGNED = 'TASK_DETAIL_ASSIGNED'
export const TASK_DETAIL_SUMMARY = 'TASK_DETAIL_SUMMARY'
export const TASK_DETAIL_STATUS_MACRO = 'TASK_DETAIL_STATUS_MACRO'
export const TASK_DETAIL_STATUS_MICRO = 'TASK_DETAIL_STATUS_MICRO'

//Task Prioritisation
export const TASK_DETAIL_BUSINESS_DRIVEN = 'TASK_DETAIL_BUSINESS_DRIVEN'
export const TASK_DETAIL_FOCUS = 'TASK_DETAIL_FOCUS'
export const TASK_DETAIL_IMPORTANT = 'TASK_DETAIL_IMPORTANT'
export const TASK_DETAIL_URGENT = 'TASK_DETAIL_URGENT'
export const TASK_DETAIL_EFFORT = 'TASK_DETAIL_EFFORT'
export const TASK_DETAIL_CATEGORY = 'TASK_DETAIL_CATEGORY'
export const TASK_DETAIL_PIPELINE = 'TASK_DETAIL_PIPELINE'
export const TASK_DETAIL_COMMENT = 'TASK_DETAIL_COMMENT'

//Task Notes
export const TASK_DETAIL_NOTE = 'TASK_DETAIL_NOTE'

// Add New Task
export const CLEAR_TASK_DETAIL = 'CLEAR_TASK_DETAIL'
export const NEW_TASK = 'NEW_TASK'


// Complete View
export const VIEW = 'VIEW'

// One user View
export const VIEW_ONE_USER = 'VIEW_ONE_USER'